services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: monitor-hub-springboot

    restart: unless-stopped

    depends_on:
      - postgres

    ports:
      - "${PORT:-8080}:8080"
      - "5005:5005"

    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monitorhub
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      JAVA_TOOL_OPTIONS: >
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  postgres:
    image: postgres:17

    container_name: monitor-hub-postgres

    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: ${POSTGRES_DB:-monitorhub}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      TZ: UTC

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


