spring.application.name=monitor-hub-springboot
server.port=8080

spring.mvc.problemdetails.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
monitor.scan.cron=0 * * * * *
monitor.batch-size=50
management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus,health,metrics