spring.application.name=monitor-hub-springboot
server.port=8080

spring.mvc.problemdetails.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
monitor.scan.cron=0 * * * * *
monitor.batch-size=50

jwt.secret=${JWT_SECRET:monitor-hub-secret-key-para-assinatura-hs256-troque-em-producao}
jwt.access-token-expiration-ms=900000
jwt.refresh-token-expiration-ms=604800000