spring.datasource.url=jdbc:postgresql://localhost:5432/monitorhub
spring.datasource.username=postgres
spring.datasource.password=postgres
management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus,health,metrics